### ISSUE TITLE
0.4.1 crashes on windows if there is no internet connection, android works

### ISSUE THREAD

**Issue by mrb1778** [yupswing/akifox-asynchttp#12]

**Comment by yupswing** [comment]
any log?
what target? CPP?

**Comment by yupswing** [comment]
I've tested all the SAMPLES on Windows 7 with no internet connection and I've got _no errors at all_ but normal behaviour.

Check your code, it could be some other problem not related to the library.

I close the issue for now.
Reopen it if you have more info to provide (sample code or detailed platform + detailed target + request full code)

Thanks
yup
