### ISSUE TITLE
accessing external url on localhost

### ISSUE THREAD

**Issue by man2** [yupswing/akifox-asynchttp#15]
Is there a way to access external url on localhost?
I got this on console

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://www.google.com/. (Reason: CORS request failed).

**Comment by yupswing** [comment]
If you are using Flash or Javascript target there are certain security restriction (as I wrote in the guide and in the code).
This is done (not by me) to prevent cross-site calls for security reasons.

You can make cross-site requests implementing some policies on the web server you need to call. (if, obviously, you have control of that server)
_Flash_: http://www.adobe.com/devnet/adobe-media-server/articles/cross-domain-xml-for-streaming.html
_Javascript_: https://en.wikipedia.org/wiki/Cross-origin_resource_sharing

You will never be able to access third-party websites with no XSS policies like google.com

---

In all the other targets (CPP, Java, Neko and so on) you don't have any restriction.

Hope this will answer your question.
