### ISSUE TITLE
sync request not working?

### ISSUE THREAD

**Issue by ramsestom** [yupswing/akifox-asynchttp#18]
Hi
  The async:false option do not seem to work (or I didn't understand how to make it work maybe).

If I do:

var answer:String = "";

var request = new HttpRequest( {
    url : "http://www.google.com",
    method : HttpMethod.GET,
    headers : new HttpHeaders({
        'Cache-Control':'no-cache'
    }),
    timeout : 10,
    async : false,
    http11 : true,
    callback : function(response:HttpResponse):Void 
    {
        if (response.isOK) {
          answer = response.content;
          trace("Callback answer: " + answer );
        }
        else {
          trace("Error");  
          return null;
        }
    }  
});

request.send();

trace("Answer: " + answer );

I have:

Answer:
Callback answer: [code from the www.google.com page]

So how can I make sync request so that my code wait for the response to continue?

**Comment by yupswing** [comment]
It works perfectly on CPP (just tested). It is supported in JS as well.
It is not supported in Flash. Are you using flash target?
