### ISSUE TITLE
app crashes when  Exit();

### ISSUE THREAD

**Issue by chuanhaisoft** [yupswing/akifox-asynchttp#2]
android

1.
var request = new AsyncHttpRequest("http://www.00000.com/123.php",
function(response:AsyncHttpResponse):Void {
if (response.isOK) {
trace(response.content);
trace('DONE (HTTP STATUS ${response.status})');
} else {
trace('ERROR (HTTP STATUS ${response.status})');
}
}

);
request.send();

2.
Exit();

3.

then app crashes

**Comment by yupswing** [comment]
I don't know what is `Exit();`
Do you mean [Sys.exit()](http://api.haxe.org/Sys.html#exit)?
Can you explain?

**Comment by chuanhaisoft** [comment]
yes , Sys.exit()

**Comment by chuanhaisoft** [comment]
sorry,it is my code bug

**Comment by yupswing** [comment]
brill. no worries ;)
