### ISSUE TITLE
hxssl unmaintained

### ISSUE THREAD

**Issue by mastef** [yupswing/akifox-asynchttp#26]
Since hxssl is now depreciated ( https://github.com/tong/hxssl ) any plans to make akifox work with Haxe 3 out of the box?

**Comment by yupswing** [comment]
I'll do some testing next week and I'll let you know.
This could be very nice ;)

**Comment by mastef** [comment]
Would be cool! Do you also have some simple example on how to get https requests to work? Seems to be a real pain, especially platform cross-compatible ( e.g. neko works, but iOS/Android fails, etc ) or Cert errors popping up.

Also what's the big advantage of using haxe.http vs using URLRequest?

**Comment by yupswing** [comment]
Hxssl removed, using haxe ssl support out of the box.
Check it out and open an issue if you find problems.
Have a great day :)
