### ISSUE TITLE
HTTP/1.1 performance MUCH slower than HTTP/1.0

### ISSUE THREAD

**Issue by PaulGene** [yupswing/akifox-asynchttp#32]
Since using asynchttp I've had much slower performance (almost unusable) compared to OpenFL's URLLoader, so I tried a few different options and discovered setting the http11 flag to false gives me the same performance as URLLoader.

I'm not sure if this is a bug or is just caused by the extra complexity of HTTP/1.1 but i thought i should mention it anyway.

**Comment by yupswing** [comment]
ok, this really depends on the target.

Flash target uses native URLLoader in any case.
Javascript target uses native haxe.Http
all the rest uses the custom HTTP client.

now, I've tried to test the difference between HTTP11=true and HTTP11=false
I cannot see any particular difference (tried CPP, NEKO and JAVA)

Here you can see a test of 10 loads of the wikipedia haxe page with HTTP11 true and 10 loads of the same page with HTTP11 false

```
Main.hx:46: HTTP 1.1 ACTIVE
Main.hx:24: 0.421
Main.hx:24: 0.38
Main.hx:24: 0.384
Main.hx:24: 0.38
Main.hx:24: 0.376
Main.hx:24: 0.391
Main.hx:24: 0.38
Main.hx:24: 0.396
Main.hx:24: 0.39
Main.hx:24: 0.376
Main.hx:60: HTTP 1.1 INACTIVE
Main.hx:24: 0.383
Main.hx:24: 0.393
Main.hx:24: 0.38
Main.hx:24: 0.385
Main.hx:24: 0.412
Main.hx:24: 0.385
Main.hx:24: 0.395
Main.hx:24: 0.383
Main.hx:24: 0.381
Main.hx:24: 0.586
```

The timing per request is basically the same (around 0.4 sec to perform the request and get the response).

If you look at the code you can see that using http 1.0 or 1.1 does not change a lot.
It just changes the request sent to the server (saying "I support HTTP 1.1 responses").
The code handles always HTTP 1.1 responses (which, in our case, just give more options to transfer the data), and it happen to be that a HTTP 1.0 response is compatible with a HTTP 1.1 (not the opposite).

So in the end, I assume your problem depends by the server you are targeting your requests to.
Try with wikipedia and let me know.

**Comment by PaulGene** [comment]
Sorry forgot to mention I'm testing C++ targets (Windows / iOS / Android)

Bizarrely HTTP/1.1 seems to be fine loading http://sticklebackgames.com ( Under a second average )  but not http://sticklebackgames.com/test.php (  5+ seconds average,  with HTTP/1.0 its about 0.2 seconds average)

test.php is just a blank script,  hopefully you will see similar results.

**Comment by yupswing** [comment]
I've found the problem. On HTTP/1.1 you need to specify if you want the connection to be kept open or to close it immediately after the response as in HTTP/1.0.
Now I tell explicitly to the server (using HTTP/1.1) to close the connection.

This change fixes the issue.
The release has been submitted, just update the library to the last version.

**Comment by PaulGene** [comment]
Confirmed fixed =o)
