### ISSUE TITLE
Consider allowing any HTTP method

### ISSUE THREAD

**Issue by Ohmnivore** [yupswing/akifox-asynchttp#35]
Browsing through the source, I can see that at its core the method is just a String value. Yet, the library restricts it to the usual four REST methods. In my use-case I only need to use a PATCH request, but there's so many other methods in the wild that I don't think it makes sense to artificially restrict them.

**Comment by yupswing** [comment]
I agree with you completely. Actually I've just updated the library to v0.4.7 to comply with your request.

You have to understand that the javascript target accept only GET and POST (it is an haxe.Http limitation). At the beginning of the library I've tried to limit a lot of stuff to have the exact same features in every target. Slowly this requirement was impossible to stand, so the library has 'mostly' the exact features on every target.
This is such a case where it is better to allow everything and to point out that one target has a limitation.

Thank you for your feedback.
PS: you can update the library directly from haxelib

**Comment by Ohmnivore** [comment]
Awesome! Thank you!
