### ISSUE TITLE
Support SSL for iOS and Android

### ISSUE THREAD

**Issue by yupswing** [yupswing/akifox-asynchttp#8]
The SSL Library ([hxssl](https://github.com/tong/hxssl)) needs to be compiled for iOS and Android.
(NDLLs needed for those platform)

It looks like something quite painful 
https://github.com/tong/hxssl/issues/
- [ ] iOS
- [ ] Android

**Comment by jeremyfa** [comment]
Today, I succeeded to make hxssl build for iOS (with an embedded openssl binary for iOS, which doesn't have it otherwise). 
For now this work is in my fork of hxssl: https://github.com/jeremyfa/hxssl but I will test aquifox-asynchttp with it first. If it works, I will make a pull request to hxssl and move on to make it build for Android :)

**Comment by yupswing** [comment]
you are Great!

**Comment by jeremyfa** [comment]
Some updates: when trying to run connect through SSL socket on iOS, it throws me an `"ERROR"` message. I mean, litterally, a string message containing `"ERROR"`.

Doing caveman debugging to find out what is going on...

**Comment by jeremyfa** [comment]
Well, when calling `SSL_connect` it get an `SSL_ERROR_ZERO_RETURN` error.
So, this is where I am:
1. I did build HXSSL with openSSL embedded in it for iOS
2. I succeeded to make it run in an iOS project, but I get this `SSL_ERROR_ZERO_RETURN` when trying to connect to an HTTPS URL.

I don't know why the ssl socket fails to connect :(

**Comment by jeremyfa** [comment]
I think I will stop my investigations here for now. I don't really have much time to do deep debugging of openSSL. My changes to make hxssl build for iOS (with embedded openssl 1.0.2a built with https://github.com/x2on/OpenSSL-for-iPhone) can be seen in my fork (https://github.com/jeremyfa/hxssl) if somebody want to continue investigating...

**Comment by PaulGene** [comment]
Any updates on this I really wanted to used this to get past some problems with OpenFL + URLLoader, but i need SSL on iOS and Android!

**Comment by yupswing** [comment]
No idea how to do it, I need help on this.
That is why I tagged this feature as HELP WANTED ;)

**Comment by jeremyfa** [comment]
Several months ago I tried to make hxssl work on iOS, without success (it did build, but was still throwing errors).
A compromise (even if it requires more code) might be to just bind to Cocoa NSURLSession for iOS and HTTPUrlConnection on Android. They both support SSL out of the box.

**Comment by PaulGene** [comment]
Gah its totally above my head to help with this :(

**Comment by grisevg** [comment]
Native extension around NSURLSession and HTTPUrlConnection sounds like a great idea. It's weird there isn't one already

**Comment by PaulGene** [comment]
Would this help ? https://github.com/HaxeFoundation/hxcpp/pull/393#issuecomment-204337790

**Comment by PaulGene** [comment]
Just tested SSL + Android after the recent updates and can confirm its working nicely!

Will try iOS soon...

**Comment by yupswing** [comment]
Brilliant. It should work as well on ios. Open a new issue in case of problems.
